Shop/Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('auth/', include('app_auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/app_auth/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('signin/',
         LoginView.as_view(template_name='app_auth/login.html', form_class=LoginForm, redirect_authenticated_user=True,
                           next_page='core:core'), name='signin'),
    path('logout/', LogoutView.as_view(template_name='app_auth/logout.html'), name='logout')
]

Shop/core/urls.py
from django.urls import path, include

from . import views
from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='core'),
    path('category/<int:catalog_id>', views.category_products, name='category_products'),
    path('products/', views.products, name='products'),
    path('add_product/', views.add_product, name='add_product'),
    path('catalog/', views.catalog, name='catalog'),
    path('product_detail/<int:product_id>', views.product_detail, name='product_detail'),
]

Shop/app_auth/models.py
from django.db import models

# Create your models here.

Shop/core/models.py
from datetime import datetime

from django.db import models
from django.db.models import ImageField


class Category(models.Model):
    name = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='catalog', blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    price = models.IntegerField(null=False)
    description = models.CharField(max_length=255, blank=True)
    image = models.ImageField(upload_to='products', blank=True)

    created_at = models.DateTimeField(default=datetime.now(), blank=True)

    def __str__(self):
        return self.name

Shop/app_auth/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=25, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ('username', 'password')

Shop/core/forms.py
from django.forms import CharField, IntegerField, ModelForm, TextInput, ModelChoiceField, FileField, Textarea, Select
from .models import Product, Category


class AddProduct(ModelForm):
    name = CharField(max_length=50, widget=TextInput(attrs={'class': "form-control", "id": "InputProductName"}))
    price = IntegerField(widget=TextInput(attrs={'class': "form-control", "id": "InputProductPrice"}))
    description = CharField(max_length=255, widget=Textarea(attrs={'class': "form-control", "id": "InputProductDescription"}))
    category = ModelChoiceField(queryset=Category.objects.all(), empty_label=None, widget=Select(attrs={'class': "form-control", "id": "InputProductCategory"}))
    image = FileField(label='Choose file')

    class Meta:
        model = Product
        fields = ['category', 'name', 'price', 'description', 'image']

Shop/app_auth/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    template_name = 'app_auth/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="core:core")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо {username}. Ваш акаунт успішно створено")
            return redirect(to="core:core")
        return render(request, self.template_name, {"form": form})

Shop/core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .forms import AddProduct
from .models import Product, Category


def index(request):
    return render(request, 'core/index.html')


def catalog(request):
    categories = Category.objects.all()
    return render(request, 'core/catalog.html', {'categories': categories})


def category_products(request, catalog_id):
    category = get_object_or_404(Category, id=catalog_id)
    products = Product.objects.filter(category=category)
    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    products_page = paginator.get_page(page_number)
    return render(request, 'core/products.html', {'category': category, 'products_page': products_page})


def products(request):
    products = Product.objects.all()
    paginator = Paginator(products, 10)
    page_number = request.GET.get('page')
    products_page = paginator.get_page(page_number)
    return render(request, 'core/products.html', {'products_page': products_page})


def product_detail(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'core/product_detail.html', {'product': product})


def add_product(request):
    if request.method == 'POST':
        form = AddProduct(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('core:catalog')
    else:
        form = AddProduct()
    return render(request, 'core/add_product.html', {'form': form})

Shop/app_auth/templates/app_auth/login.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

Shop/app_auth/templates/app_auth/logout.html
{% extends 'core/base.html' %}

{% block content %}

<div class="container mt-3">
    <h1>Повертайтесь будь ласка!</h1>
</div>

{% endblock %}

Shop/app_auth/templates/app_auth/register.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

Shop/core/templates/core/add_product.html
{% extends 'core/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            {{ form.category.label_tag }}
            {{ form.category.as_widget }}
        </div>
        <div class="mb-3">
            {{ form.name.label_tag }}
            {{ form.name.as_widget }}
        </div>
        <div class="mb-3">
            {{ form.price.label_tag }}
            {{ form.price.as_widget }}
        </div>
        <div class="mb-3">
            {{ form.description.label_tag }}
            {{ form.description.as_widget }}
        </div>
        <div class="mb-3">
            {{ form.image.label_tag }}
            {{ form.image.as_widget }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
{% endblock %}

Shop/core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PCtech</title>
    {% load static %}
    <link href="img/favicon.ico" rel="icon">
    <link href="{% static 'core/main.css' %}" rel="stylesheet">
    <link href="{% static 'core/style.css' %}" rel="stylesheet">
    <link href="{% static 'core/style.scss' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="/" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">PC</span>tech</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">0</span>
                </a>
            </div>
        </div>
    </div>
            <div class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold">
                        <span class="text-primary font-weight-bold border px-3 mr-1">PC</span>tech
                    </h1>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'core:core' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'core:catalog' %}" class="nav-item nav-link">Catalog</a>
                        <a href="contact.html" class="nav-item nav-link">Contact</a>
                </div>
                <div class="navbar-nav ml-auto py-0">
                    {% if user.is_authenticated %}
                        <form action="{% url 'app_auth:logout' %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-item nav-link btn btn-link" style="border: none; cursor: pointer;">
                                Logout
                            </button>
                        </form>
                    {% else %}
                        <a href="{% url 'app_auth:signin' %}" class="nav-item nav-link">Login</a>
                        <a href="{% url 'app_auth:signup' %}" class="nav-item nav-link">Register</a>
                    {% endif %}
                </div>
            </div>
    </div>


    <!-- Topbar End -->
    {% block content %}
    {% endblock %}

    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">PC</span>tech</h1>
                </a>
                <p>Computer store.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a><br>
                    Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>

</body>
</html>

Shop/core/templates/core/catalog.html
{% extends "core/base.html" %}


{% block content %}
<div class="cards">
    {% for category in categories %}
    <div class="card">
        <div class="card__top">
        <!-- Изображение-ссылка товара -->
        <a href="{% url 'core:category_products' category.id %}" class="card__image">
          <img
            src="{{ category.image.url }}"
            alt="{{category.name}}"
          />
        </a>
         </div>
        <div class="card__bottom">
        <a href="#" class="card__title">
            {{category.name}}
        </a>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

Shop/core/templates/core/product_detail.html
{% extends "core/base.html" %}

{% block content %}
    <div class="product-detail">
        <img src="{{product.image.url}}" class="img-fluid mx-auto" style="max-width: 700px;" alt="Изображение продукта">
        <h1>{{ product.name }}</h1>
        <h2><a href="{% url 'core:catalog' %}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}}

Shop/core/templates/core/products.html
{% extends 'core/base.html' %}

{% block content %}
<head>
    <title>Продукты категории {{ category.name }}</title>
</head>
<div class="cards">
    {% for product in products_page %}
    <div class="card">
      <div class="card__top">
        <!-- Изображение-ссылка товара -->
        <a href="{% url 'core:product_detail' product.id %}" class="card__image">
          <img
            src="{{ product.image.url }}"
            alt="{{ product.name }}"
          />
        </a>
      </div>
      <div class="card__bottom">
        <div class="card__prices">
          <div class="card__price card__price--common">Price: {{product.price}}</div>
        </div>
        <a href="#" class="card__title">
            {{product.name}}
        </a>
        <button class="card__add">В корзину</button>
      </div>
    </div>
    {% endfor %}
</div>
<nav aria-label="Навигация по страницам сайта">
    <ul class="pagination d-flex justify-content-center" >
        {% if products_page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ products_page.previous_page_number }}">
                <span aria-hidden="true">←</span> Previous
            </a>
        </li>
        {% endif %}
        {% if products_page.has_next %}
        <li class="page-item">
            <a class="page-link " href="?page={{ products_page.next_page_number }}">
                Next <span aria-hidden="true">→</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endblock %}